// Import all your trimmed blocks data statically

// Grade 3 English Book - All available pages (10-138)
import page10TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_10/grade_3_english_book.pdf_page_10_trimmed_blocks.json';
import page100G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_100/grade_3_english_book.pdf_page_100_trimmed_blocks.json';
import page101G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_101/grade_3_english_book.pdf_page_101_trimmed_blocks.json';
import page102G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_102/grade_3_english_book.pdf_page_102_trimmed_blocks.json';
import page103G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_103/grade_3_english_book.pdf_page_103_trimmed_blocks.json';
import page104G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_104/grade_3_english_book.pdf_page_104_trimmed_blocks.json';
import page105G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_105/grade_3_english_book.pdf_page_105_trimmed_blocks.json';
import page106G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_106/grade_3_english_book.pdf_page_106_trimmed_blocks.json';
import page107G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_107/grade_3_english_book.pdf_page_107_trimmed_blocks.json';
import page108G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_108/grade_3_english_book.pdf_page_108_trimmed_blocks.json';
import page109G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_109/grade_3_english_book.pdf_page_109_trimmed_blocks.json';
import page11TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_11/grade_3_english_book.pdf_page_11_trimmed_blocks.json';
import page110G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_110/grade_3_english_book.pdf_page_110_trimmed_blocks.json';
import page111G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_111/grade_3_english_book.pdf_page_111_trimmed_blocks.json';
import page112G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_112/grade_3_english_book.pdf_page_112_trimmed_blocks.json';
import page113G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_113/grade_3_english_book.pdf_page_113_trimmed_blocks.json';
import page114G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_114/grade_3_english_book.pdf_page_114_trimmed_blocks.json';
import page115G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_115/grade_3_english_book.pdf_page_115_trimmed_blocks.json';
import page116G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_116/grade_3_english_book.pdf_page_116_trimmed_blocks.json';
import page117G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_117/grade_3_english_book.pdf_page_117_trimmed_blocks.json';
import page118G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_118/grade_3_english_book.pdf_page_118_trimmed_blocks.json';
import page119G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_119/grade_3_english_book.pdf_page_119_trimmed_blocks.json';
import page12TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_12/grade_3_english_book.pdf_page_12_trimmed_blocks.json';
import page120G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_120/grade_3_english_book.pdf_page_120_trimmed_blocks.json';
import page121G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_121/grade_3_english_book.pdf_page_121_trimmed_blocks.json';
import page122G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_122/grade_3_english_book.pdf_page_122_trimmed_blocks.json';
import page123G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_123/grade_3_english_book.pdf_page_123_trimmed_blocks.json';
import page124G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_124/grade_3_english_book.pdf_page_124_trimmed_blocks.json';
import page125G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_125/grade_3_english_book.pdf_page_125_trimmed_blocks.json';
import page126G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_126/grade_3_english_book.pdf_page_126_trimmed_blocks.json';
import page127G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_127/grade_3_english_book.pdf_page_127_trimmed_blocks.json';
import page128G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_128/grade_3_english_book.pdf_page_128_trimmed_blocks.json';
import page129G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_129/grade_3_english_book.pdf_page_129_trimmed_blocks.json';
import page13TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_13/grade_3_english_book.pdf_page_13_trimmed_blocks.json';
import page130G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_130/grade_3_english_book.pdf_page_130_trimmed_blocks.json';
import page131G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_131/grade_3_english_book.pdf_page_131_trimmed_blocks.json';
import page132G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_132/grade_3_english_book.pdf_page_132_trimmed_blocks.json';
import page133G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_133/grade_3_english_book.pdf_page_133_trimmed_blocks.json';
import page134G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_134/grade_3_english_book.pdf_page_134_trimmed_blocks.json';
import page135G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_135/grade_3_english_book.pdf_page_135_trimmed_blocks.json';
import page136G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_136/grade_3_english_book.pdf_page_136_trimmed_blocks.json';
import page137G3TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_137/grade_3_english_book.pdf_page_137_trimmed_blocks.json';
import page14TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_14/grade_3_english_book.pdf_page_14_trimmed_blocks.json';
import page15TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_15/grade_3_english_book.pdf_page_15_trimmed_blocks.json';
import page16TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_16/grade_3_english_book.pdf_page_16_trimmed_blocks.json';
import page17TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_17/grade_3_english_book.pdf_page_17_trimmed_blocks.json';
import page18TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_18/grade_3_english_book.pdf_page_18_trimmed_blocks.json';
import page19TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_19/grade_3_english_book.pdf_page_19_trimmed_blocks.json';
import page20TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_20/grade_3_english_book.pdf_page_20_trimmed_blocks.json';
// import page21TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_21/grade_3_english_book.pdf_page_21_trimmed_blocks.json';
import page22TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_22/grade_3_english_book.pdf_page_22_trimmed_blocks.json';
import page23TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_23/grade_3_english_book.pdf_page_23_trimmed_blocks.json';
import page24TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_24/grade_3_english_book.pdf_page_24_trimmed_blocks.json';
import page25TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_25/grade_3_english_book.pdf_page_25_trimmed_blocks.json';
import page26TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_26/grade_3_english_book.pdf_page_26_trimmed_blocks.json';
import page27TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_27/grade_3_english_book.pdf_page_27_trimmed_blocks.json';
import page28TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_28/grade_3_english_book.pdf_page_28_trimmed_blocks.json';
import page29TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_29/grade_3_english_book.pdf_page_29_trimmed_blocks.json';
import page30TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_30/grade_3_english_book.pdf_page_30_trimmed_blocks.json';
import page31TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_31/grade_3_english_book.pdf_page_31_trimmed_blocks.json';
import page32TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_32/grade_3_english_book.pdf_page_32_trimmed_blocks.json';
import page33TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_33/grade_3_english_book.pdf_page_33_trimmed_blocks.json';
import page34TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_34/grade_3_english_book.pdf_page_34_trimmed_blocks.json';
import page35TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_35/grade_3_english_book.pdf_page_35_trimmed_blocks.json';
import page36TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_36/grade_3_english_book.pdf_page_36_trimmed_blocks.json';
// import page37TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_37/grade_3_english_book.pdf_page_37_trimmed_blocks.json';
import page38TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_38/grade_3_english_book.pdf_page_38_trimmed_blocks.json';
import page39TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_39/grade_3_english_book.pdf_page_39_trimmed_blocks.json';
import page40TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_40/grade_3_english_book.pdf_page_40_trimmed_blocks.json';
import page41TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_41/grade_3_english_book.pdf_page_41_trimmed_blocks.json';
import page42TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_42/grade_3_english_book.pdf_page_42_trimmed_blocks.json';
import page43TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_43/grade_3_english_book.pdf_page_43_trimmed_blocks.json';
import page44TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_44/grade_3_english_book.pdf_page_44_trimmed_blocks.json';
import page45TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_45/grade_3_english_book.pdf_page_45_trimmed_blocks.json';
import page46TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_46/grade_3_english_book.pdf_page_46_trimmed_blocks.json';
import page47TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_47/grade_3_english_book.pdf_page_47_trimmed_blocks.json';
import page48TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_48/grade_3_english_book.pdf_page_48_trimmed_blocks.json';
import page49TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_49/grade_3_english_book.pdf_page_49_trimmed_blocks.json';
import page50TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_50/grade_3_english_book.pdf_page_50_trimmed_blocks.json';
import page51TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_51/grade_3_english_book.pdf_page_51_trimmed_blocks.json';
import page52TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_52/grade_3_english_book.pdf_page_52_trimmed_blocks.json';
import page53TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_53/grade_3_english_book.pdf_page_53_trimmed_blocks.json';
import page54TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_54/grade_3_english_book.pdf_page_54_trimmed_blocks.json';
import page55TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_55/grade_3_english_book.pdf_page_55_trimmed_blocks.json';
import page56TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_56/grade_3_english_book.pdf_page_56_trimmed_blocks.json';
import page57TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_57/grade_3_english_book.pdf_page_57_trimmed_blocks.json';
import page58TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_58/grade_3_english_book.pdf_page_58_trimmed_blocks.json';
import page59TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_59/grade_3_english_book.pdf_page_59_trimmed_blocks.json';
import page60TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_60/grade_3_english_book.pdf_page_60_trimmed_blocks.json';
import page61TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_61/grade_3_english_book.pdf_page_61_trimmed_blocks.json';
import page62TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_62/grade_3_english_book.pdf_page_62_trimmed_blocks.json';
import page63TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_63/grade_3_english_book.pdf_page_63_trimmed_blocks.json';
import page64TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_64/grade_3_english_book.pdf_page_64_trimmed_blocks.json';
import page65TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_65/grade_3_english_book.pdf_page_65_trimmed_blocks.json';
import page66TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_66/grade_3_english_book.pdf_page_66_trimmed_blocks.json';
import page67TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_67/grade_3_english_book.pdf_page_67_trimmed_blocks.json';
import page68TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_68/grade_3_english_book.pdf_page_68_trimmed_blocks.json';
import page69TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_69/grade_3_english_book.pdf_page_69_trimmed_blocks.json';
import page70TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_70/grade_3_english_book.pdf_page_70_trimmed_blocks.json';
import page71TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_71/grade_3_english_book.pdf_page_71_trimmed_blocks.json';
import page72TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_72/grade_3_english_book.pdf_page_72_trimmed_blocks.json';
import page73TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_73/grade_3_english_book.pdf_page_73_trimmed_blocks.json';
import page74TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_74/grade_3_english_book.pdf_page_74_trimmed_blocks.json';
import page75TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_75/grade_3_english_book.pdf_page_75_trimmed_blocks.json';
import page76TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_76/grade_3_english_book.pdf_page_76_trimmed_blocks.json';
import page77TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_77/grade_3_english_book.pdf_page_77_trimmed_blocks.json';
import page78TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_78/grade_3_english_book.pdf_page_78_trimmed_blocks.json';
import page79TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_79/grade_3_english_book.pdf_page_79_trimmed_blocks.json';
import page80TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_80/grade_3_english_book.pdf_page_80_trimmed_blocks.json';
import page81TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_81/grade_3_english_book.pdf_page_81_trimmed_blocks.json';
import page82TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_82/grade_3_english_book.pdf_page_82_trimmed_blocks.json';
import page83TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_83/grade_3_english_book.pdf_page_83_trimmed_blocks.json';
import page84TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_84/grade_3_english_book.pdf_page_84_trimmed_blocks.json';
import page85TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_85/grade_3_english_book.pdf_page_85_trimmed_blocks.json';
import page86TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_86/grade_3_english_book.pdf_page_86_trimmed_blocks.json';
import page87TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_87/grade_3_english_book.pdf_page_87_trimmed_blocks.json';
import page88TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_88/grade_3_english_book.pdf_page_88_trimmed_blocks.json';
import page89TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_89/grade_3_english_book.pdf_page_89_trimmed_blocks.json';
import page90TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_90/grade_3_english_book.pdf_page_90_trimmed_blocks.json';
import page91TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_91/grade_3_english_book.pdf_page_91_trimmed_blocks.json';
import page92TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_92/grade_3_english_book.pdf_page_92_trimmed_blocks.json';
import page93TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_93/grade_3_english_book.pdf_page_93_trimmed_blocks.json';
import page94TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_94/grade_3_english_book.pdf_page_94_trimmed_blocks.json';
import page95TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_95/grade_3_english_book.pdf_page_95_trimmed_blocks.json';
import page96TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_96/grade_3_english_book.pdf_page_96_trimmed_blocks.json';
import page97TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_97/grade_3_english_book.pdf_page_97_trimmed_blocks.json';
import page98TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_98/grade_3_english_book.pdf_page_98_trimmed_blocks.json';
import page99TrimmedBlocks from '@/data/grade_3_english_book/grade_3_english_book_page_99/grade_3_english_book.pdf_page_99_trimmed_blocks.json';

// Grade 4 English Book (pages 10-119)
import page10G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_10/grade_4_english_book.pdf_page_10_trimmed_blocks.json';
import page100G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_100/grade_4_english_book.pdf_page_100_trimmed_blocks.json';
import page101G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_101/grade_4_english_book.pdf_page_101_trimmed_blocks.json';
import page102G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_102/grade_4_english_book.pdf_page_102_trimmed_blocks.json';
import page103G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_103/grade_4_english_book.pdf_page_103_trimmed_blocks.json';
import page104G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_104/grade_4_english_book.pdf_page_104_trimmed_blocks.json';
import page105G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_105/grade_4_english_book.pdf_page_105_trimmed_blocks.json';
import page106G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_106/grade_4_english_book.pdf_page_106_trimmed_blocks.json';
import page107G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_107/grade_4_english_book.pdf_page_107_trimmed_blocks.json';
import page108G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_108/grade_4_english_book.pdf_page_108_trimmed_blocks.json';
import page109G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_109/grade_4_english_book.pdf_page_109_trimmed_blocks.json';
import page11G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_11/grade_4_english_book.pdf_page_11_trimmed_blocks.json';
import page110G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_110/grade_4_english_book.pdf_page_110_trimmed_blocks.json';
import page111G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_111/grade_4_english_book.pdf_page_111_trimmed_blocks.json';
import page112G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_112/grade_4_english_book.pdf_page_112_trimmed_blocks.json';
import page113G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_113/grade_4_english_book.pdf_page_113_trimmed_blocks.json';
import page114G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_114/grade_4_english_book.pdf_page_114_trimmed_blocks.json';
import page115G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_115/grade_4_english_book.pdf_page_115_trimmed_blocks.json';
import page116G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_116/grade_4_english_book.pdf_page_116_trimmed_blocks.json';
import page117G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_117/grade_4_english_book.pdf_page_117_trimmed_blocks.json';
import page118G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_118/grade_4_english_book.pdf_page_118_trimmed_blocks.json';
import page119G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_119/grade_4_english_book.pdf_page_119_trimmed_blocks.json';
import page12G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_12/grade_4_english_book.pdf_page_12_trimmed_blocks.json';
import page13G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_13/grade_4_english_book.pdf_page_13_trimmed_blocks.json';
import page14G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_14/grade_4_english_book.pdf_page_14_trimmed_blocks.json';
import page15G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_15/grade_4_english_book.pdf_page_15_trimmed_blocks.json';
import page16G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_16/grade_4_english_book.pdf_page_16_trimmed_blocks.json';
import page17G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_17/grade_4_english_book.pdf_page_17_trimmed_blocks.json';
import page18G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_18/grade_4_english_book.pdf_page_18_trimmed_blocks.json';
import page19G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_19/grade_4_english_book.pdf_page_19_trimmed_blocks.json';
import page20G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_20/grade_4_english_book.pdf_page_20_trimmed_blocks.json';
import page21G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_21/grade_4_english_book.pdf_page_21_trimmed_blocks.json';
import page22G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_22/grade_4_english_book.pdf_page_22_trimmed_blocks.json';
import page23G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_23/grade_4_english_book.pdf_page_23_trimmed_blocks.json';
import page24G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_24/grade_4_english_book.pdf_page_24_trimmed_blocks.json';
import page25G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_25/grade_4_english_book.pdf_page_25_trimmed_blocks.json';
import page26G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_26/grade_4_english_book.pdf_page_26_trimmed_blocks.json';
import page27G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_27/grade_4_english_book.pdf_page_27_trimmed_blocks.json';
import page28G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_28/grade_4_english_book.pdf_page_28_trimmed_blocks.json';
import page29G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_29/grade_4_english_book.pdf_page_29_trimmed_blocks.json';
import page30G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_30/grade_4_english_book.pdf_page_30_trimmed_blocks.json';
import page31G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_31/grade_4_english_book.pdf_page_31_trimmed_blocks.json';
import page32G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_32/grade_4_english_book.pdf_page_32_trimmed_blocks.json';
import page33G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_33/grade_4_english_book.pdf_page_33_trimmed_blocks.json';
import page34G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_34/grade_4_english_book.pdf_page_34_trimmed_blocks.json';
import page35G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_35/grade_4_english_book.pdf_page_35_trimmed_blocks.json';
import page36G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_36/grade_4_english_book.pdf_page_36_trimmed_blocks.json';
import page37G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_37/grade_4_english_book.pdf_page_37_trimmed_blocks.json';
import page38G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_38/grade_4_english_book.pdf_page_38_trimmed_blocks.json';
import page39G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_39/grade_4_english_book.pdf_page_39_trimmed_blocks.json';
import page40G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_40/grade_4_english_book.pdf_page_40_trimmed_blocks.json';
import page41G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_41/grade_4_english_book.pdf_page_41_trimmed_blocks.json';
import page42G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_42/grade_4_english_book.pdf_page_42_trimmed_blocks.json';
import page43G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_43/grade_4_english_book.pdf_page_43_trimmed_blocks.json';
import page44G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_44/grade_4_english_book.pdf_page_44_trimmed_blocks.json';
import page45G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_45/grade_4_english_book.pdf_page_45_blocks.json';
import page46G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_46/grade_4_english_book.pdf_page_46_trimmed_blocks.json';
import page47G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_47/grade_4_english_book.pdf_page_47_trimmed_blocks.json';
import page48G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_48/grade_4_english_book.pdf_page_48_trimmed_blocks.json';
import page49G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_49/grade_4_english_book.pdf_page_49_trimmed_blocks.json';
import page50G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_50/grade_4_english_book.pdf_page_50_trimmed_blocks.json';
import page51G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_51/grade_4_english_book.pdf_page_51_trimmed_blocks.json';
import page52G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_52/grade_4_english_book.pdf_page_52_trimmed_blocks.json';
import page53G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_53/grade_4_english_book.pdf_page_53_trimmed_blocks.json';
import page54G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_54/grade_4_english_book.pdf_page_54_trimmed_blocks.json';
import page55G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_55/grade_4_english_book.pdf_page_55_trimmed_blocks.json';
import page56G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_56/grade_4_english_book.pdf_page_56_trimmed_blocks.json';
import page57G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_57/grade_4_english_book.pdf_page_57_trimmed_blocks.json';
import page58G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_58/grade_4_english_book.pdf_page_58_trimmed_blocks.json';
import page59G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_59/grade_4_english_book.pdf_page_59_trimmed_blocks.json';
import page60G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_60/grade_4_english_book.pdf_page_60_trimmed_blocks.json';
import page61G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_61/grade_4_english_book.pdf_page_61_trimmed_blocks.json';
import page62G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_62/grade_4_english_book.pdf_page_62_trimmed_blocks.json';
import page63G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_63/grade_4_english_book.pdf_page_63_trimmed_blocks.json';
import page64G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_64/grade_4_english_book.pdf_page_64_trimmed_blocks.json';
import page65G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_65/grade_4_english_book.pdf_page_65_trimmed_blocks.json';
import page66G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_66/grade_4_english_book.pdf_page_66_trimmed_blocks.json';
import page67G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_67/grade_4_english_book.pdf_page_67_trimmed_blocks.json';
import page68G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_68/grade_4_english_book.pdf_page_68_trimmed_blocks.json';
import page69G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_69/grade_4_english_book.pdf_page_69_trimmed_blocks.json';
import page70G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_70/grade_4_english_book.pdf_page_70_trimmed_blocks.json';
import page71G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_71/grade_4_english_book.pdf_page_71_trimmed_blocks.json';
import page72G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_72/grade_4_english_book.pdf_page_72_trimmed_blocks.json';
import page73G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_73/grade_4_english_book.pdf_page_73_trimmed_blocks.json';
import page74G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_74/grade_4_english_book.pdf_page_74_trimmed_blocks.json';
import page75G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_75/grade_4_english_book.pdf_page_75_blocks.json';
import page76G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_76/grade_4_english_book.pdf_page_76_trimmed_blocks.json';
import page77G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_77/grade_4_english_book.pdf_page_77_trimmed_blocks.json';
import page78G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_78/grade_4_english_book.pdf_page_78_trimmed_blocks.json';
import page79G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_79/grade_4_english_book.pdf_page_79_trimmed_blocks.json';
import page80G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_80/grade_4_english_book.pdf_page_80_trimmed_blocks.json';
import page81G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_81/grade_4_english_book.pdf_page_81_trimmed_blocks.json';
import page82G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_82/grade_4_english_book.pdf_page_82_trimmed_blocks.json';
import page83G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_83/grade_4_english_book.pdf_page_83_trimmed_blocks.json';
import page84G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_84/grade_4_english_book.pdf_page_84_trimmed_blocks.json';
import page85G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_85/grade_4_english_book.pdf_page_85_trimmed_blocks.json';
import page86G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_86/grade_4_english_book.pdf_page_86_trimmed_blocks.json';
import page87G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_87/grade_4_english_book.pdf_page_87_blocks.json';
import page88G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_88/grade_4_english_book.pdf_page_88_trimmed_blocks.json';
import page89G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_89/grade_4_english_book.pdf_page_89_trimmed_blocks.json';
import page90G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_90/grade_4_english_book.pdf_page_90_trimmed_blocks.json';
import page91G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_91/grade_4_english_book.pdf_page_91_trimmed_blocks.json';
import page92G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_92/grade_4_english_book.pdf_page_92_trimmed_blocks.json';
import page93G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_93/grade_4_english_book.pdf_page_93_trimmed_blocks.json';
import page94G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_94/grade_4_english_book.pdf_page_94_trimmed_blocks.json';
import page95G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_95/grade_4_english_book.pdf_page_95_trimmed_blocks.json';
import page96G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_96/grade_4_english_book.pdf_page_96_trimmed_blocks.json';
import page97G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_97/grade_4_english_book.pdf_page_97_trimmed_blocks.json';
import page98G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_98/grade_4_english_book.pdf_page_98_trimmed_blocks.json';
import page99G4TrimmedBlocks from '@/data/grade_4_english_book/grade_4_english_book_page_99/grade_4_english_book.pdf_page_99_trimmed_blocks.json';

export interface TrimmedBlockData {
  [blockId: string]: {
    text: string;
    words: string[];
    bounding_boxes: number[][] | number[][][]; // Can be either format
    ssml: string;
    dialog?: string;
    person_type?: string;
    voice_id?: string;
    timing?: Array<{
      time: number;
      type: string;
      start: number;
      end: number;
      value: string;
    }>;
  };
}

export class TrimmedBlocksDataService {
  private static instance: TrimmedBlocksDataService;
  private grade3DataMap: Map<number, TrimmedBlockData> = new Map();
  private grade4DataMap: Map<number, TrimmedBlockData> = new Map();

  static getInstance(): TrimmedBlocksDataService {
    if (!TrimmedBlocksDataService.instance) {
      TrimmedBlocksDataService.instance = new TrimmedBlocksDataService();
    }
    return TrimmedBlocksDataService.instance;
  }

  constructor() {
    // Initialize Grade 3 English Book pages (10-137)
    this.grade3DataMap.set(10, page10TrimmedBlocks as any);
    this.grade3DataMap.set(11, page11TrimmedBlocks as any);
    this.grade3DataMap.set(12, page12TrimmedBlocks as any);
    this.grade3DataMap.set(13, page13TrimmedBlocks as any);
    this.grade3DataMap.set(14, page14TrimmedBlocks as any);
    this.grade3DataMap.set(15, page15TrimmedBlocks as any);
    this.grade3DataMap.set(16, page16TrimmedBlocks as any);
    this.grade3DataMap.set(17, page17TrimmedBlocks as any);
    this.grade3DataMap.set(18, page18TrimmedBlocks as any);
    this.grade3DataMap.set(19, page19TrimmedBlocks as any);
    this.grade3DataMap.set(20, page20TrimmedBlocks as any);
    // this.grade3DataMap.set(21, page21TrimmedBlocks as any);
    this.grade3DataMap.set(22, page22TrimmedBlocks as any);
    this.grade3DataMap.set(23, page23TrimmedBlocks as any);
    this.grade3DataMap.set(24, page24TrimmedBlocks as any);
    this.grade3DataMap.set(25, page25TrimmedBlocks as any);
    this.grade3DataMap.set(26, page26TrimmedBlocks as any);
    this.grade3DataMap.set(27, page27TrimmedBlocks as any);
    this.grade3DataMap.set(28, page28TrimmedBlocks as any);
    this.grade3DataMap.set(29, page29TrimmedBlocks as any);
    this.grade3DataMap.set(30, page30TrimmedBlocks as any);
    this.grade3DataMap.set(31, page31TrimmedBlocks as any);
    this.grade3DataMap.set(32, page32TrimmedBlocks as any);
    this.grade3DataMap.set(33, page33TrimmedBlocks as any);
    this.grade3DataMap.set(34, page34TrimmedBlocks as any);
    this.grade3DataMap.set(35, page35TrimmedBlocks as any);
    this.grade3DataMap.set(36, page36TrimmedBlocks as any);
    // this.grade3DataMap.set(37, page37TrimmedBlocks as any);
    this.grade3DataMap.set(38, page38TrimmedBlocks as any);
    this.grade3DataMap.set(39, page39TrimmedBlocks as any);
    this.grade3DataMap.set(40, page40TrimmedBlocks as any);
    this.grade3DataMap.set(41, page41TrimmedBlocks as any);
    this.grade3DataMap.set(42, page42TrimmedBlocks as any);
    this.grade3DataMap.set(43, page43TrimmedBlocks as any);
    this.grade3DataMap.set(44, page44TrimmedBlocks as any);
    this.grade3DataMap.set(45, page45TrimmedBlocks as any);
    this.grade3DataMap.set(46, page46TrimmedBlocks as any);
    this.grade3DataMap.set(47, page47TrimmedBlocks as any);
    this.grade3DataMap.set(48, page48TrimmedBlocks as any);
    this.grade3DataMap.set(49, page49TrimmedBlocks as any);
    this.grade3DataMap.set(50, page50TrimmedBlocks as any);
    this.grade3DataMap.set(51, page51TrimmedBlocks as any);
    this.grade3DataMap.set(52, page52TrimmedBlocks as any);
    this.grade3DataMap.set(53, page53TrimmedBlocks as any);
    this.grade3DataMap.set(54, page54TrimmedBlocks as any);
    this.grade3DataMap.set(55, page55TrimmedBlocks as any);
    this.grade3DataMap.set(56, page56TrimmedBlocks as any);
    this.grade3DataMap.set(57, page57TrimmedBlocks as any);
    this.grade3DataMap.set(58, page58TrimmedBlocks as any);
    this.grade3DataMap.set(59, page59TrimmedBlocks as any);
    this.grade3DataMap.set(60, page60TrimmedBlocks as any);
    this.grade3DataMap.set(61, page61TrimmedBlocks as any);
    this.grade3DataMap.set(62, page62TrimmedBlocks as any);
    this.grade3DataMap.set(63, page63TrimmedBlocks as any);
    this.grade3DataMap.set(64, page64TrimmedBlocks as any);
    this.grade3DataMap.set(65, page65TrimmedBlocks as any);
    this.grade3DataMap.set(66, page66TrimmedBlocks as any);
    this.grade3DataMap.set(67, page67TrimmedBlocks as any);
    this.grade3DataMap.set(68, page68TrimmedBlocks as any);
    this.grade3DataMap.set(69, page69TrimmedBlocks as any);
    this.grade3DataMap.set(70, page70TrimmedBlocks as any);
    this.grade3DataMap.set(71, page71TrimmedBlocks as any);
    this.grade3DataMap.set(72, page72TrimmedBlocks as any);
    this.grade3DataMap.set(73, page73TrimmedBlocks as any);
    this.grade3DataMap.set(74, page74TrimmedBlocks as any);
    this.grade3DataMap.set(75, page75TrimmedBlocks as any);
    this.grade3DataMap.set(76, page76TrimmedBlocks as any);
    this.grade3DataMap.set(77, page77TrimmedBlocks as any);
    this.grade3DataMap.set(78, page78TrimmedBlocks as any);
    this.grade3DataMap.set(79, page79TrimmedBlocks as any);
    this.grade3DataMap.set(80, page80TrimmedBlocks as any);
    this.grade3DataMap.set(81, page81TrimmedBlocks as any);
    this.grade3DataMap.set(82, page82TrimmedBlocks as any);
    this.grade3DataMap.set(83, page83TrimmedBlocks as any);
    this.grade3DataMap.set(84, page84TrimmedBlocks as any);
    this.grade3DataMap.set(85, page85TrimmedBlocks as any);
    this.grade3DataMap.set(86, page86TrimmedBlocks as any);
    this.grade3DataMap.set(87, page87TrimmedBlocks as any);
    this.grade3DataMap.set(88, page88TrimmedBlocks as any);
    this.grade3DataMap.set(89, page89TrimmedBlocks as any);
    this.grade3DataMap.set(90, page90TrimmedBlocks as any);
    this.grade3DataMap.set(91, page91TrimmedBlocks as any);
    this.grade3DataMap.set(92, page92TrimmedBlocks as any);
    this.grade3DataMap.set(93, page93TrimmedBlocks as any);
    this.grade3DataMap.set(94, page94TrimmedBlocks as any);
    this.grade3DataMap.set(95, page95TrimmedBlocks as any);
    this.grade3DataMap.set(96, page96TrimmedBlocks as any);
    this.grade3DataMap.set(97, page97TrimmedBlocks as any);
    this.grade3DataMap.set(98, page98TrimmedBlocks as any);
    this.grade3DataMap.set(99, page99TrimmedBlocks as any);
    this.grade3DataMap.set(100, page100G3TrimmedBlocks as any);
    this.grade3DataMap.set(101, page101G3TrimmedBlocks as any);
    this.grade3DataMap.set(102, page102G3TrimmedBlocks as any);
    this.grade3DataMap.set(103, page103G3TrimmedBlocks as any);
    this.grade3DataMap.set(104, page104G3TrimmedBlocks as any);
    this.grade3DataMap.set(105, page105G3TrimmedBlocks as any);
    this.grade3DataMap.set(106, page106G3TrimmedBlocks as any);
    this.grade3DataMap.set(107, page107G3TrimmedBlocks as any);
    this.grade3DataMap.set(108, page108G3TrimmedBlocks as any);
    this.grade3DataMap.set(109, page109G3TrimmedBlocks as any);
    this.grade3DataMap.set(110, page110G3TrimmedBlocks as any);
    this.grade3DataMap.set(111, page111G3TrimmedBlocks as any);
    this.grade3DataMap.set(112, page112G3TrimmedBlocks as any);
    this.grade3DataMap.set(113, page113G3TrimmedBlocks as any);
    this.grade3DataMap.set(114, page114G3TrimmedBlocks as any);
    this.grade3DataMap.set(115, page115G3TrimmedBlocks as any);
    this.grade3DataMap.set(116, page116G3TrimmedBlocks as any);
    this.grade3DataMap.set(117, page117G3TrimmedBlocks as any);
    this.grade3DataMap.set(118, page118G3TrimmedBlocks as any);
    this.grade3DataMap.set(119, page119G3TrimmedBlocks as any);
    this.grade3DataMap.set(120, page120G3TrimmedBlocks as any);
    this.grade3DataMap.set(121, page121G3TrimmedBlocks as any);
    this.grade3DataMap.set(122, page122G3TrimmedBlocks as any);
    this.grade3DataMap.set(123, page123G3TrimmedBlocks as any);
    this.grade3DataMap.set(124, page124G3TrimmedBlocks as any);
    this.grade3DataMap.set(125, page125G3TrimmedBlocks as any);
    this.grade3DataMap.set(126, page126G3TrimmedBlocks as any);
    this.grade3DataMap.set(127, page127G3TrimmedBlocks as any);
    this.grade3DataMap.set(128, page128G3TrimmedBlocks as any);
    this.grade3DataMap.set(129, page129G3TrimmedBlocks as any);
    this.grade3DataMap.set(130, page130G3TrimmedBlocks as any);
    this.grade3DataMap.set(131, page131G3TrimmedBlocks as any);
    this.grade3DataMap.set(132, page132G3TrimmedBlocks as any);
    this.grade3DataMap.set(133, page133G3TrimmedBlocks as any);
    this.grade3DataMap.set(134, page134G3TrimmedBlocks as any);
    this.grade3DataMap.set(135, page135G3TrimmedBlocks as any);
    this.grade3DataMap.set(136, page136G3TrimmedBlocks as any);
    this.grade3DataMap.set(137, page137G3TrimmedBlocks as any);

    // Grade 4 English Book pages (mapped to avoid conflicts with Grade 3)
    this.grade4DataMap.set(10, page10G4TrimmedBlocks as any);
    this.grade4DataMap.set(11, page11G4TrimmedBlocks as any);
    this.grade4DataMap.set(12, page12G4TrimmedBlocks as any);
    this.grade4DataMap.set(13, page13G4TrimmedBlocks as any);
    this.grade4DataMap.set(14, page14G4TrimmedBlocks as any);
    this.grade4DataMap.set(15, page15G4TrimmedBlocks as any);
    this.grade4DataMap.set(16, page16G4TrimmedBlocks as any);
    this.grade4DataMap.set(17, page17G4TrimmedBlocks as any);
    this.grade4DataMap.set(18, page18G4TrimmedBlocks as any);
    this.grade4DataMap.set(19, page19G4TrimmedBlocks as any);
    this.grade4DataMap.set(20, page20G4TrimmedBlocks as any);
    this.grade4DataMap.set(21, page21G4TrimmedBlocks as any);
    this.grade4DataMap.set(22, page22G4TrimmedBlocks as any);
    this.grade4DataMap.set(23, page23G4TrimmedBlocks as any);
    this.grade4DataMap.set(24, page24G4TrimmedBlocks as any);
    this.grade4DataMap.set(25, page25G4TrimmedBlocks as any);
    this.grade4DataMap.set(26, page26G4TrimmedBlocks as any);
    this.grade4DataMap.set(27, page27G4TrimmedBlocks as any);
    this.grade4DataMap.set(28, page28G4TrimmedBlocks as any);
    this.grade4DataMap.set(29, page29G4TrimmedBlocks as any);
    this.grade4DataMap.set(30, page30G4TrimmedBlocks as any);
    this.grade4DataMap.set(31, page31G4TrimmedBlocks as any);
    this.grade4DataMap.set(32, page32G4TrimmedBlocks as any);
    this.grade4DataMap.set(33, page33G4TrimmedBlocks as any);
    this.grade4DataMap.set(34, page34G4TrimmedBlocks as any);
    this.grade4DataMap.set(35, page35G4TrimmedBlocks as any);
    this.grade4DataMap.set(36, page36G4TrimmedBlocks as any);
    this.grade4DataMap.set(37, page37G4TrimmedBlocks as any);
    this.grade4DataMap.set(38, page38G4TrimmedBlocks as any);
    this.grade4DataMap.set(39, page39G4TrimmedBlocks as any);
    this.grade4DataMap.set(40, page40G4TrimmedBlocks as any);
    this.grade4DataMap.set(41, page41G4TrimmedBlocks as any);
    this.grade4DataMap.set(42, page42G4TrimmedBlocks as any);
    this.grade4DataMap.set(43, page43G4TrimmedBlocks as any);
    this.grade4DataMap.set(44, page44G4TrimmedBlocks as any);
    this.grade4DataMap.set(45, page45G4TrimmedBlocks as any);
    this.grade4DataMap.set(46, page46G4TrimmedBlocks as any);
    this.grade4DataMap.set(47, page47G4TrimmedBlocks as any);
    this.grade4DataMap.set(48, page48G4TrimmedBlocks as any);
    this.grade4DataMap.set(49, page49G4TrimmedBlocks as any);
    this.grade4DataMap.set(50, page50G4TrimmedBlocks as any);
    this.grade4DataMap.set(51, page51G4TrimmedBlocks as any);
    this.grade4DataMap.set(52, page52G4TrimmedBlocks as any);
    this.grade4DataMap.set(53, page53G4TrimmedBlocks as any);
    this.grade4DataMap.set(54, page54G4TrimmedBlocks as any);
    this.grade4DataMap.set(55, page55G4TrimmedBlocks as any);
    this.grade4DataMap.set(56, page56G4TrimmedBlocks as any);
    this.grade4DataMap.set(57, page57G4TrimmedBlocks as any);
    this.grade4DataMap.set(58, page58G4TrimmedBlocks as any);
    this.grade4DataMap.set(59, page59G4TrimmedBlocks as any);
    this.grade4DataMap.set(60, page60G4TrimmedBlocks as any);
    this.grade4DataMap.set(61, page61G4TrimmedBlocks as any);
    this.grade4DataMap.set(62, page62G4TrimmedBlocks as any);
    this.grade4DataMap.set(63, page63G4TrimmedBlocks as any);
    this.grade4DataMap.set(64, page64G4TrimmedBlocks as any);
    this.grade4DataMap.set(65, page65G4TrimmedBlocks as any);
    this.grade4DataMap.set(66, page66G4TrimmedBlocks as any);
    this.grade4DataMap.set(67, page67G4TrimmedBlocks as any);
    this.grade4DataMap.set(68, page68G4TrimmedBlocks as any);
    this.grade4DataMap.set(69, page69G4TrimmedBlocks as any);
    this.grade4DataMap.set(70, page70G4TrimmedBlocks as any);
    this.grade4DataMap.set(71, page71G4TrimmedBlocks as any);
    this.grade4DataMap.set(72, page72G4TrimmedBlocks as any);
    this.grade4DataMap.set(73, page73G4TrimmedBlocks as any);
    this.grade4DataMap.set(74, page74G4TrimmedBlocks as any);
    this.grade4DataMap.set(75, page75G4TrimmedBlocks as any);
    this.grade4DataMap.set(76, page76G4TrimmedBlocks as any);
    this.grade4DataMap.set(77, page77G4TrimmedBlocks as any);
    this.grade4DataMap.set(78, page78G4TrimmedBlocks as any);
    this.grade4DataMap.set(79, page79G4TrimmedBlocks as any);
    this.grade4DataMap.set(80, page80G4TrimmedBlocks as any);
    this.grade4DataMap.set(81, page81G4TrimmedBlocks as any);
    this.grade4DataMap.set(82, page82G4TrimmedBlocks as any);
    this.grade4DataMap.set(83, page83G4TrimmedBlocks as any);
    this.grade4DataMap.set(84, page84G4TrimmedBlocks as any);
    this.grade4DataMap.set(85, page85G4TrimmedBlocks as any);
    this.grade4DataMap.set(86, page86G4TrimmedBlocks as any);
    this.grade4DataMap.set(87, page87G4TrimmedBlocks as any);
    this.grade4DataMap.set(88, page88G4TrimmedBlocks as any);    
    this.grade4DataMap.set(89, page89G4TrimmedBlocks as any);
    this.grade4DataMap.set(90, page90G4TrimmedBlocks as any);
    this.grade4DataMap.set(91, page91G4TrimmedBlocks as any);
    this.grade4DataMap.set(92, page92G4TrimmedBlocks as any);
    this.grade4DataMap.set(93, page93G4TrimmedBlocks as any);
    this.grade4DataMap.set(94, page94G4TrimmedBlocks as any);
    this.grade4DataMap.set(95, page95G4TrimmedBlocks as any);
    this.grade4DataMap.set(96, page96G4TrimmedBlocks as any);
    this.grade4DataMap.set(97, page97G4TrimmedBlocks as any);
    this.grade4DataMap.set(98, page98G4TrimmedBlocks as any);
    this.grade4DataMap.set(99, page99G4TrimmedBlocks as any);
    this.grade4DataMap.set(100, page100G4TrimmedBlocks as any);
    this.grade4DataMap.set(101, page101G4TrimmedBlocks as any);
    this.grade4DataMap.set(102, page102G4TrimmedBlocks as any);
    this.grade4DataMap.set(103, page103G4TrimmedBlocks as any);
    this.grade4DataMap.set(104, page104G4TrimmedBlocks as any);
    this.grade4DataMap.set(105, page105G4TrimmedBlocks as any);
    this.grade4DataMap.set(106, page106G4TrimmedBlocks as any);
    this.grade4DataMap.set(107, page107G4TrimmedBlocks as any);
    this.grade4DataMap.set(108, page108G4TrimmedBlocks as any);
    this.grade4DataMap.set(109, page109G4TrimmedBlocks as any);
    this.grade4DataMap.set(110, page110G4TrimmedBlocks as any);
    this.grade4DataMap.set(111, page111G4TrimmedBlocks as any);
    this.grade4DataMap.set(112, page112G4TrimmedBlocks as any);
    this.grade4DataMap.set(113, page113G4TrimmedBlocks as any);
    this.grade4DataMap.set(114, page114G4TrimmedBlocks as any);
    this.grade4DataMap.set(115, page115G4TrimmedBlocks as any);
    this.grade4DataMap.set(116, page116G4TrimmedBlocks as any);
    this.grade4DataMap.set(117, page117G4TrimmedBlocks as any);
    this.grade4DataMap.set(118, page118G4TrimmedBlocks as any);
    this.grade4DataMap.set(119, page119G4TrimmedBlocks as any);

    console.log('TrimmedBlocksDataService initialized with Grade 3 pages:', Array.from(this.grade3DataMap.keys()).length, 'and Grade 4 pages:', Array.from(this.grade4DataMap.keys()).length);
  }

  getTrimmedBlocksForPage(pageNumber: number, bookTitle?: string): TrimmedBlockData | null {
    // Determine which data map to use based on book title
    let dataMap: Map<number, TrimmedBlockData>;
    
    if (bookTitle && (bookTitle.toLowerCase().includes('grade 4') || bookTitle.toLowerCase().includes('grade_4'))) {
      dataMap = this.grade4DataMap;
    } else {
      // Default to Grade 3 for backward compatibility
      dataMap = this.grade3DataMap;
    }
    
    const data = dataMap.get(pageNumber);
    if (data) {
      console.log(`Found trimmed blocks data for page ${pageNumber} in ${bookTitle || 'Grade 3 book'}:`, Object.keys(data).length, 'blocks');
      return data;
    } else {
      console.warn(`No trimmed blocks data found for page ${pageNumber} in ${bookTitle || 'Grade 3 book'}`);
      return null;
    }
  }

  hasDataForPage(pageNumber: number, bookTitle?: string): boolean {
    if (bookTitle && (bookTitle.toLowerCase().includes('grade 4') || bookTitle.toLowerCase().includes('grade_4'))) {
      return this.grade4DataMap.has(pageNumber);
    } else {
      return this.grade3DataMap.has(pageNumber);
    }
  }

  getAvailablePages(bookTitle?: string): number[] {
    if (bookTitle && (bookTitle.toLowerCase().includes('grade 4') || bookTitle.toLowerCase().includes('grade_4'))) {
      return Array.from(this.grade4DataMap.keys());
    } else {
      return Array.from(this.grade3DataMap.keys());
    }
  }
}
