const fs = require('fs');
const path = require('path');

// Function to get page numbers from a book directory
function getPageNumbers(bookName) {
  const dataDir = path.join(__dirname, '..', 'data', bookName);
  if (!fs.existsSync(dataDir)) {
    return [];
  }
  
  const pages = fs.readdirSync(dataDir)
    .filter(item => {
      const itemPath = path.join(dataDir, item);
      return fs.statSync(itemPath).isDirectory() && item.includes('_page_');
    })
    .map(item => {
      const match = item.match(/_page_(\d+)/);
      return match ? parseInt(match[1]) : null;
    })
    .filter(num => num !== null)
    .sort((a, b) => a - b);
    
  return pages;
}

// Get page numbers for all books
const demoPages = getPageNumbers('demo_book');
const grade3Pages = getPageNumbers('grade_3_english_book');
const grade4Pages = getPageNumbers('grade_4_english_book');
const grade5Pages = getPageNumbers('grade_5_english_book');
const grade6Pages = getPageNumbers('grade_6_english_book');
const grade7Pages = getPageNumbers('grade_7_english_book_unit_1');

console.log('Found Demo pages:', demoPages.length);
console.log('Found Grade 3 pages:', grade3Pages.length);
console.log('Found Grade 4 pages:', grade4Pages.length);
console.log('Found Grade 5 pages:', grade5Pages.length);
console.log('Found Grade 6 pages:', grade6Pages.length);
console.log('Found Grade 7 pages:', grade7Pages.length);

// Generate the audio resolver content
let content = `// Auto-generated AudioResolver service
// This file is generated by scripts/generateAudioResolver.js

`;

// Function to add audio imports for a book
function addAudioImports(bookName, pages, prefix) {
  pages.forEach(pageNum => {
    const pageDir = path.join(__dirname, '..', 'data', bookName, `${bookName}_page_${pageNum}`);
    
    if (fs.existsSync(pageDir)) {
      const audioFiles = fs.readdirSync(pageDir).filter(file => file.endsWith('_audio.mp3') && !file.includes('_slow_'));
      
      if (audioFiles.length > 0) {
        content += `// ${bookName} Page ${pageNum} audio files\n`;
        audioFiles.forEach(file => {
          const blockMatch = file.match(/block_(\d+)_(\d+)_audio\.mp3/);
          if (blockMatch) {
            const blockId = blockMatch[2];
            content += `const ${prefix}page${pageNum}_block${blockId} = require('../data/${bookName}/${bookName}_page_${pageNum}/${file}');\n`;
          }
        });
        content += '\n';
      }
    }
  });
}

// Function to add SLOW audio imports for a book
function addSlowAudioImports(bookName, pages, prefix) {
  pages.forEach(pageNum => {
    const pageDir = path.join(__dirname, '..', 'data', bookName, `${bookName}_page_${pageNum}`);
    
    if (fs.existsSync(pageDir)) {
      const audioFiles = fs.readdirSync(pageDir).filter(file => file.endsWith('_slow_audio.mp3'));
      
      if (audioFiles.length > 0) {
        content += `// ${bookName} Page ${pageNum} SLOW audio files\n`;
        audioFiles.forEach(file => {
          const blockMatch = file.match(/block_(\d+)_(\d+)_slow_audio\.mp3/);
          if (blockMatch) {
            const blockId = blockMatch[2];
            content += `const ${prefix}page${pageNum}_block${blockId}_slow = require('../data/${bookName}/${bookName}_page_${pageNum}/${file}');\n`;
          }
        });
        content += '\n';
      }
    }
  });
}

// Add audio imports for all books
addAudioImports('demo_book', demoPages, 'demo_');
addAudioImports('grade_3_english_book', grade3Pages, 'g3_');
addAudioImports('grade_4_english_book', grade4Pages, 'g4_');
addAudioImports('grade_5_english_book', grade5Pages, 'g5_');
addAudioImports('grade_6_english_book', grade6Pages, 'g6_');
addAudioImports('grade_7_english_book_unit_1', grade7Pages, 'g7_');

// Add SLOW audio imports
content += `// Slow audio files for all grades\n`;
addSlowAudioImports('demo_book', demoPages, 'demo_');
addSlowAudioImports('grade_3_english_book', grade3Pages, 'g3_');
addSlowAudioImports('grade_5_english_book', grade5Pages, 'g5_');
addSlowAudioImports('grade_6_english_book', grade6Pages, 'g6_');
addSlowAudioImports('grade_7_english_book_unit_1', grade7Pages, 'g7_');

// Create audio mappings objects for both books
content += `// Audio mappings by book and page\n`;
content += `const demoAudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;

// Add Demo mappings
addAudioMappings('demo_book', demoPages, 'demo_');
content += `};\n\n`;

content += `const grade3AudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;

// Function to add audio mappings for a book
function addAudioMappings(bookName, pages, prefix, isGrade4 = false) {
  pages.forEach(pageNum => {
    const pageDir = path.join(__dirname, '..', 'data', bookName, `${bookName}_page_${pageNum}`);
    
    if (fs.existsSync(pageDir)) {
      const audioFiles = fs.readdirSync(pageDir).filter(file => file.endsWith('_audio.mp3') && !file.includes('_slow_'));
      
      if (audioFiles.length > 0) {
        content += `  '${pageNum}': {\n`;
        
        audioFiles.forEach(file => {
          const blockMatch = file.match(/block_(\d+)_(\d+)_audio\.mp3/);
          if (blockMatch) {
            const blockId = blockMatch[2];
            content += `    '${blockId}': ${prefix}page${pageNum}_block${blockId},\n`;
          }
        });
        
        content += `  },\n`;
      }
    }
  });
}

// Function to add SLOW audio mappings for a book
function addSlowAudioMappings(bookName, pages, prefix) {
  pages.forEach(pageNum => {
    const pageDir = path.join(__dirname, '..', 'data', bookName, `${bookName}_page_${pageNum}`);
    
    if (fs.existsSync(pageDir)) {
      const audioFiles = fs.readdirSync(pageDir).filter(file => file.endsWith('_slow_audio.mp3'));
      
      if (audioFiles.length > 0) {
        content += `  '${pageNum}': {\n`;
        
        audioFiles.forEach(file => {
          const blockMatch = file.match(/block_(\d+)_(\d+)_slow_audio\.mp3/);
          if (blockMatch) {
            const blockId = blockMatch[2];
            content += `    '${blockId}': ${prefix}page${pageNum}_block${blockId}_slow,\n`;
          }
        });
        
        content += `  },\n`;
      }
    }
  });
}

// Add Grade 3 mappings
addAudioMappings('grade_3_english_book', grade3Pages, 'g3_');
content += `};\n\n`;

// Add Grade 4 mappings
content += `const grade4AudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addAudioMappings('grade_4_english_book', grade4Pages, 'g4_');
content += `};\n\n`;

// Add Grade 5 mappings
content += `const grade5AudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addAudioMappings('grade_5_english_book', grade5Pages, 'g5_');
content += `};\n\n`;

// Add Grade 6 mappings
content += `const grade6AudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addAudioMappings('grade_6_english_book', grade6Pages, 'g6_');
content += `};\n\n`;

// Add Grade 7 mappings
content += `const grade7AudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addAudioMappings('grade_7_english_book_unit_1', grade7Pages, 'g7_');
content += `};\n\n`;

// Add Demo SLOW mappings
content += `const demoSlowAudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addSlowAudioMappings('demo_book', demoPages, 'demo_');
content += `};\n\n`;

// Add Grade 3 SLOW mappings
content += `const grade3SlowAudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addSlowAudioMappings('grade_3_english_book', grade3Pages, 'g3_');
content += `};\n\n`;

// Add Grade 5 SLOW mappings
content += `const grade5SlowAudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addSlowAudioMappings('grade_5_english_book', grade5Pages, 'g5_');
content += `};\n\n`;

// Add Grade 6 SLOW mappings
content += `const grade6SlowAudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addSlowAudioMappings('grade_6_english_book', grade6Pages, 'g6_');
content += `};\n\n`;

// Add Grade 7 SLOW mappings
content += `const grade7SlowAudioMappings: { [pageNumber: string]: { [blockId: string]: any } } = {\n`;
addSlowAudioMappings('grade_7_english_book_unit_1', grade7Pages, 'g7_');
content += `};\n\n`;

// Add the book-aware service class
content += `export class AudioResolver {
  static resolveAudio(pageNumber: number, blockId: string, bookTitle?: string, isSlowMode?: boolean): any | null {
    // If slow mode is enabled, try slow audio first for supported grades
    if (isSlowMode) {
      let slowMappings = null;
      
      if (!bookTitle || bookTitle.toLowerCase().includes('demo')) {
        slowMappings = demoSlowAudioMappings;
      } else if (bookTitle.toLowerCase().includes('grade 3') || bookTitle.toLowerCase().includes('grade_3')) {
        slowMappings = grade3SlowAudioMappings;
      } else if (bookTitle.toLowerCase().includes('grade 5') || bookTitle.toLowerCase().includes('grade_5')) {
        slowMappings = grade5SlowAudioMappings;
      } else if (bookTitle.toLowerCase().includes('grade 6') || bookTitle.toLowerCase().includes('grade_6')) {
        slowMappings = grade6SlowAudioMappings;
      } else if (bookTitle.toLowerCase().includes('grade 7') || bookTitle.toLowerCase().includes('grade_7')) {
        slowMappings = grade7SlowAudioMappings;
      }
      
      if (slowMappings) {
        const slowPageAudio = slowMappings[pageNumber.toString()];
        if (slowPageAudio && slowPageAudio[blockId]) {
          return slowPageAudio[blockId];
        }
        // Fall back to normal audio if slow audio not available
        console.log(\`No slow audio found for page \${pageNumber}, block \${blockId}, using normal audio\`);
      }
    }
    
    // Determine which audio mappings to use based on book title
    let audioMappings;
    if (bookTitle && (bookTitle.toLowerCase().includes('demo'))) {
      audioMappings = demoAudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 4') || bookTitle.toLowerCase().includes('grade_4'))) {
      audioMappings = grade4AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 5') || bookTitle.toLowerCase().includes('grade_5'))) {
      audioMappings = grade5AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 6') || bookTitle.toLowerCase().includes('grade_6'))) {
      audioMappings = grade6AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 7') || bookTitle.toLowerCase().includes('grade_7'))) {
      audioMappings = grade7AudioMappings;
    } else {
      // Default to Grade 3 for backward compatibility
      audioMappings = grade3AudioMappings;
    }
    
    const pageAudio = audioMappings[pageNumber.toString()];
    if (!pageAudio) {
      console.log(\`No audio mappings found for page \${pageNumber} in \${bookTitle || 'Grade 3 book'}\`);
      return null;
    }
    
    const audio = pageAudio[blockId];
    if (!audio) {
      console.log(\`No audio found for page \${pageNumber}, block \${blockId} in \${bookTitle || 'Grade 3 book'}\`);
      return null;
    }
    
    return audio;
  }
  
  static hasAudioForPage(pageNumber: number, bookTitle?: string): boolean {
    let audioMappings;
    if (bookTitle && (bookTitle.toLowerCase().includes('demo'))) {
      audioMappings = demoAudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 4') || bookTitle.toLowerCase().includes('grade_4'))) {
      audioMappings = grade4AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 5') || bookTitle.toLowerCase().includes('grade_5'))) {
      audioMappings = grade5AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 7') || bookTitle.toLowerCase().includes('grade_7'))) {
      audioMappings = grade7AudioMappings;
    } else {
      audioMappings = grade3AudioMappings;
    }
    return !!audioMappings[pageNumber.toString()];
  }
  
  static getAvailableBlocksForPage(pageNumber: number, bookTitle?: string): string[] {
    let audioMappings;
    if (bookTitle && (bookTitle.toLowerCase().includes('demo'))) {
      audioMappings = demoAudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 4') || bookTitle.toLowerCase().includes('grade_4'))) {
      audioMappings = grade4AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 5') || bookTitle.toLowerCase().includes('grade_5'))) {
      audioMappings = grade5AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 6') || bookTitle.toLowerCase().includes('grade_6'))) {
      audioMappings = grade6AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 6') || bookTitle.toLowerCase().includes('grade_6'))) {
      audioMappings = grade6AudioMappings;
    } else if (bookTitle && (bookTitle.toLowerCase().includes('grade 7') || bookTitle.toLowerCase().includes('grade_7'))) {
      audioMappings = grade7AudioMappings;
    } else {
      audioMappings = grade3AudioMappings;
    }
    const pageAudio = audioMappings[pageNumber.toString()];
    return pageAudio ? Object.keys(pageAudio) : [];
  }
}
`;

// Write the generated file
const outputPath = path.join(__dirname, '..', 'services', 'audioResolver.ts');
fs.writeFileSync(outputPath, content);

console.log(`Generated AudioResolver.ts with ${demoPages.length} Demo pages, ${grade3Pages.length} Grade 3 pages, ${grade4Pages.length} Grade 4 pages, ${grade5Pages.length} Grade 5 pages, ${grade6Pages.length} Grade 6 pages, and ${grade7Pages.length} Grade 7 pages`);
console.log('Demo audio mappings created for pages:', demoPages.join(', '));
console.log('Grade 3 audio mappings created for pages:', grade3Pages.join(', '));
console.log('Grade 4 audio mappings created for pages:', grade4Pages.join(', '));
console.log('Grade 5 audio mappings created for pages:', grade5Pages.join(', '));
console.log('Grade 6 audio mappings created for pages:', grade6Pages.join(', '));
console.log('Grade 7 audio mappings created for pages:', grade7Pages.join(', '));